coverage:
  status:
    project:
      default:
        # More lenient settings for a beta project
        target: auto
        threshold: 2% # More forgiving threshold
        base: auto
        # advanced settings
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

    # Add patch status to monitor coverage of new code
    patch:
      default:
        target: 70% # Reasonable target for new code
        threshold: 5% # Allow some flexibility
        base: auto

  precision: 2
  round: down
  range: "50...80" # More appropriate range for a beta project

# Comment settings to provide feedback on PRs
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false # Post a comment even if coverage doesn't change
  require_base: false
  require_head: true

ignore:
  - "src/gac/main.py" # Ignore main.py from coverage calculations
  - "tests/**/*" # Exclude test files from coverage calculation
  - "**/__version__.py" # Version file doesn't need test coverage
  - "examples/**/*" # Example files are for demonstration
  - "docs/**/*" # Documentation doesn't need coverage
